[loong.loong]
COMMON_FLAGS = "-O2 -pipe"
CHOST = "loongarch64-unknown-linux-gnu"

[loong.la64_baseline_multilib]
COMMON_FLAGS = "-O2 -pipe"
CHOST = "loongarch64-unknown-linux-gnu"

[loong.la64_baseline_lp64]
COMMON_FLAGS = "-O2 -pipe"
CHOST = "loongarch64-unknown-linux-gnu"
